import "~/styles/globals.css";
import "@uploadthing/react/styles.css";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";


import {ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton} from '@clerk/nextjs'
import UploadThingButton from "./_components/button";
export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (

    /*<html lang="en" className={`${GeistSans.variable}`}>
    <body className="bg-yellow-300">
        <div className="bg-repeat"></div>
        <div className="w-full">First Layout</div>
        <button className="btn btn-secondary btn-block">   <svg
    xmlns="http://www.w3.org/2000/svg"
    className="h-6 w-6"
    fill="bg-amber-400"
    viewBox="0 0 24 24"
    stroke="currentcolor">
    <path
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth="2"
      d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
  </svg>
        Love For Pablo</button>
        {children}
      </body>
    </html>
    */

    <ClerkProvider>
    <html lang="en">
      <body className="bg-yellow-300">
        <SignedOut>
          <SignInButton/>
        </SignedOut>
        
        <SignedIn>
          <UserButton/>
          <UploadThingButton></UploadThingButton>
        </SignedIn>
   <svg
    xmlns="http://www.w3.org/2000/svg"
    className="h-6 w-6 object-center"
    fill="bg-amber-400"
    viewBox="0 0 24 24"
    stroke="currentcolor">
    <path
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth="2"
      d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
  </svg>
        {children}
      </body>
    </html>
  </ClerkProvider>
  );
}
